spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./src/main/resources/db/testdb;DB_CLOSE_ON_EXIT=TRUE;MODE=Oracle
    username: sa
    password:
  h2:
    console:
      enabled: true
